name: Publish on PyPI

on:
  push:
    tags:
    - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
      TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine

    - name: Build and publish (helix-swarm)
      run: |
        python setup.py sdist bdist_wheel
        twine upload dist/*

    - name: Build and publish (helixswarm) alias
       run: |
        sed -i "" "s/NAME = 'helix-swarm'/NAME = 'helixswarm'/g" setup.py
        sed -i "" "s/install helix-swarm/install helixswarm/g" README.rst
        python setup.py sdist bdist_wheel
        twine upload dist/*
